### ISSUE TITLE
Allow editing of shops.yml without needing to hard reset db?

### ISSUE THREAD

**Issue by emre23q** [Unprotesting/Auto-Tune#113]
Hello,

Not sure how to add suggestions but a feature i think would be great would be the ability to edit the shop data and other configs without needing to delete the db first (causing a hard reset on the economy). Perhaps we can create/enable a setting to backup the current shop prices to a yaml file then attempt to merge it if it detects a missing db? That way a new db could be created with the prices still the same as old just with all the other data reset (a soft reset).

Thanks for hearing me out!

**Comment by LcyDev** [comment]
#110

**Comment by LcyDev** [comment]
It's a really good idea, following it in #110

**Comment by LcyDev** [comment]
@emre23q i'm going to try and code this for you (And me tbh)

**Comment by LcyDev** [comment]
This already exists please close this issue.

Here you can check out the commands #114 🙂
