### ISSUE TITLE
[BUG] buying/selling produces error

### ISSUE THREAD

**Issue by larssieboy18** [Unprotesting/Auto-Tune#14]
**Describe the bug**
People are unable to buy and sell items, as the plugin doesn't register clicking on an item right (based on the error). The error spits the following in console: [https://bin.bloom.host/ugufanilum.properties](https://bin.bloom.host/ugufanilum.properties).

**To Reproduce**
1. do /at shop
2. Click on any category and item.
3. Try to buy/sell it
4. See error (in console). For the player it seems like he didn't click on anything

**Expected behavior**
People would be able to buy and sell stuff.

**Minecraft Server Version
1.16.5, PaperMC

**Plugin List
https://file.coffee/u/k4dGKUn5BF.png

**Additional context**

**Comment by Unprotesting** [comment]
paste your shops file theres an error in it

**Comment by larssieboy18** [comment]
This is my shop.yml file: https://bin.bloom.host/qukifecuda.yaml

**Comment by Unprotesting** [comment]
what version of Auto-Tune is this?

**Comment by larssieboy18** [comment]
Prerelease 3, 0.13

**Comment by Unprotesting** [comment]
OK I'll issue a fix to catch this error but have you just tried restarting? It looks like the issue has something to do with a check for players max-buy/sell not triggering correctly when you join.

**Comment by larssieboy18** [comment]
I have had the error for multiple days straight in the past (currently the plugin is disabled due to it not working). I had disabled max-buy/sell in the config, so maybe that could be the reason for the error?
