### ISSUE TITLE
[BUG] Changing values in shop.yml doesn't work

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [Unprotesting/Auto-Tune#15]
**Describe the bug**
Changing values in shops.yml doesn't work. (Tested on both 0.13.0-pre-release-3 & 0.12.4)
Same with `/at decrease <value : %percentage>` (this part I only tested on 0.13.0-pre-release-3)
  ^ Doesn't change price
  ^ Doesn't support decreasing by a value. Only a percentage.

**To Reproduce**
1. Stop server.
2. Edit default file from 15 for coal price to:
```
shops:
  COAL:
    price: 1.56 # Old: 15
    max-buy: 80
    max-sell: 115
    section: 'Natural Resources'
```
3. Start server.
4. `/shop`
5. Look at coal price. It is still $15.
6. Try using `/at decrease coal 90` to get it to ~1.5.
7. `/shop`
8. See that it still does not change value in GUI.
9. Try selling as much coal as you can until it hits max sell limit.
10. `/shop` to see if it changes price- it doesn't.

**Expected behavior**
When I stop the server, change the price values in shops.yml, & start the server, I expect it to change them in-game to those new values.

**Screenshots**
I tried changing diamond pricing. Here are the results:
shops.yml: https://gyazo.com/68a01d27c5f2112e27dac511d3192050
In-game /shop diamond: https://gyazo.com/8adf82e365ff1c87ffc6f13ce75bcc4a

**Minecraft Server Version
Paper 1.16.5

**Plugin Version:** 
Auto-Tune-0.13.0-pre-release-3
&
Auto-Tune-0.12.4

**Latest.log:** 
<https://pastebin.com/NELSsiEq>

**Plugin List
https://gyazo.com/b02e753ca66aa6b6b4cbdaaa3119a343

**Additional context**
A suggestion- I recommend either having only 1 place you provide support/bug reports **or** manage both evenly. I reported this issue 10 days ago in a Ticket on the Discord with all info and never received a reply. I know you're busy, but 10 days without a single response from Discord staff about the issue is not good support- especially when staff are responding to #support but ignoring tickets apparently.. Awesome plugin, love the idea, but support could be improved & is unusable with this issue sadly.

**Comment by Unprotesting** [comment]
delete data.db to delete all data or do /at remove <ITEM_NAME> and restart. The $15 is saved in storage. Also try using pre-release-4 when it comes out in a few days.

**Comment by PiggiesGoSqueal** [comment]
> 
> 
> delete data.db to delete all data or do /at remove <ITEM_NAME> and restart. The $15 is saved in storage. Also try using pre-release-4 when it comes out in a few days.

Thanks for the quick reply to this ticket. 

That solved it. :) Guess I can look into using this plugin again. Hooray!
