### ISSUE TITLE
[Enhancement] Adding Support For Other Economy Plugins (Namely CMI)

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [Unprotesting/Auto-Tune#16]
Well, just noticed on the Spigot plugin resource page it requires Essentials to use this plugin. :( 

CMI is a plugin that offers economy, essentials's commands, + a LOT more. Hence why many people use it even if it is a paid plugin. I saw someone else in the Discord request CMI support being added as well. Could you please add it?

Thank you!

**Comment by Unprotesting** [comment]
Ok this will take a while but can be done.

**Comment by James76931** [comment]
+1 for this, though I'd be keen on you looking into the universal option as my server doesn't use Essentials or CMI.

**Comment by PetKCH** [comment]
+1 for this, I have switched from EssX to CMI as it provides more stuff and this is the only factor limiting me from using your plugin. Also, it would be great if the plugin would be universal and wouldn't depend on either Ess or CMI for the economy.

**Comment by valenvaio** [comment]
Everything works fine with CMI.
