### ISSUE TITLE
Latest prices

### ISSUE THREAD

**Issue by Uranusak** [Unprotesting/Auto-Tune#17]
It would be good if the plugin saved the latest prices in shops.yml, or another file, for use in the configuration, for example when shutting down the server.

**Comment by Unprotesting** [comment]
A history of prices can already be found in trade.csv and trade-short.csv, however, I can work on making it easier to view current prices. Why do you need these prices exactly in this way?

**Comment by Uranusak** [comment]
The plugin is not very stable so I would like to have the latest prices in shops.yml if I had to reset the plugin or deploy an older version so as not to lose the last price settings.

**Comment by Unprotesting** [comment]
Possibly an export prices command?

**Comment by Uranusak** [comment]
Yes, an export command for shop.yml may be enough.

**Comment by Unprotesting** [comment]
If this is still an issue please re-open it or use our discord.
