### ISSUE TITLE
[BUG] Custom currencies are not used throughout the entire plugin

### ISSUE THREAD

**Issue by James76931** [Unprotesting/Auto-Tune#18]
**Describe the bug**
Despite setting currency-symbol in the config.yml file, dollars are still displayed in many locations of the plugin.

**To Reproduce**
1. Set currency-symbol in the config.yml, I used £.
2. Execute /shop.
3. Click a shop category.
4. Click a type of block.
5. When hovering over blocks to check their prices, you will see dollars used instead of the currency-symbol value set in the config.
6. Next, type /trade.
7. Click on one of the web links displayed in chat.
8. The chart uses dollars instead of the custom currency symbol.

**Expected behaviour**
The symbol set under currency-symbol should be used throughout the entire plugin.

**Screenshots**
![image](https://user-images.githubusercontent.com/15969024/108783674-cad47500-7565-11eb-970b-14b9da588ee7.png)
![image](https://user-images.githubusercontent.com/15969024/108783625-b85a3b80-7565-11eb-9d4d-1eb832f37da8.png)

**Minecraft Server Version
1.16.5

**Plugin List
Essentials, Vault, Auto-Tune

**Comment by James76931** [comment]
This also seems to be an issue with the /gdp command.

**Comment by Unprotesting** [comment]
OK thank you. I'll fix this right away

**Comment by Unprotesting** [comment]
If this is still an issue please re-open it or use our discord.
