### ISSUE TITLE
[BUG] /at decrease does nothing

### ISSUE THREAD

**Issue by Ryoyo2** [Unprotesting/Auto-Tune#23]
**Describe the bug**
/at decrease does nothing. /at decrease [itemID] [number] will execute and show that it has decreased the price of an item by [number] percentage but does nothing. Not immediately nor on price update algorithm execution.

**To Reproduce**
1. Use something like /at decrease oak_log 50
2. See chat message in chat that the price of oak_log has been successfully decreased by 50%.
3. Price will not change, not immediately and also not when the price algorithm runs. The command has no effect.

**Expected behavior**
Command should decrease the price by either 50$ or 50% either upon command- or after price algorithm-execution.

**Screenshots**

**Minecraft Server Version**
git-Airplane-"87d4a17" (MC: 1.16.5)

**Comment by Unprotesting** [comment]
If this is still an issue please re-open it or use our discord.
