### ISSUE TITLE
[BUG] Auto-tune cannot be used with Slimefun

### ISSUE THREAD

**Issue by ImFunnySun** [Unprotesting/Auto-Tune#26]
**Describe the bug**
Auto-tune cannot be used with Slimefun

![image](https://user-images.githubusercontent.com/68582223/120097459-2153df80-c163-11eb-92a6-53a459a9798b.png)

**Minecraft Server Version
1.16.5 Paper

**Plugin List
CMI,Slimefun,Auto-tune,Vault

**Comment by adamk523** [comment]
That's news to me, I'm running all of the above plugins and experiencing no problems, aside from wishing I could sell Slimefun goodies on the shop! Which version of AT are you using?

CMI's built in economy has had a few conflicts with plugins in the past, so maybe test with a different eco?

**Comment by Ryoyo2** [comment]
You are on an outdated version of Auto-Tune and CMI might indeed be conflicting. You're also about 100 builds behind on paper. Test with all updated. The newest version of AT with some hotfixes is on the discord so I would recommend to try that one:

https://discord.com/channels/748222485975269508/748222912565215303/814267144023048243

**Comment by ImFunnySun** [comment]
![image](https://user-images.githubusercontent.com/68582223/120657203-e0d3c900-c4b6-11eb-91bf-e747a984978e.png)

**Comment by ImFunnySun** [comment]
![image](https://user-images.githubusercontent.com/68582223/120657368-04970f00-c4b7-11eb-91f7-9f4af97adeb6.png)
This is the picture of plugins.

**Comment by ImFunnySun** [comment]
> You are on an outdated version of Auto-Tune and CMI might indeed be conflicting. You're also about 100 builds behind on paper. Test with all updated. The newest version of AT with some hotfixes is on the discord so I would recommend to try that one:
> 
> https://discord.com/channels/748222485975269508/748222912565215303/814267144023048243

I updated the Auto-Tune , paper and CMI.

**Comment by ImFunnySun** [comment]
> > You are on an outdated version of Auto-Tune and CMI might indeed be conflicting. You're also about 100 builds behind on paper. Test with all updated. The newest version of AT with some hotfixes is on the discord so I would recommend to try that one:
> > https://discord.com/channels/748222485975269508/748222912565215303/814267144023048243
> 
> I updated the Auto-Tune , paper and CMI.

![image](https://user-images.githubusercontent.com/68582223/120657737-593a8a00-c4b7-11eb-820f-b0b7c30315fd.png)

**Comment by ImFunnySun** [comment]
> That's news to me, I'm running all of the above plugins and experiencing no problems, aside from wishing I could sell Slimefun goodies on the shop! Which version of AT are you using?
> 
> CMI's built in economy has had a few conflicts with plugins in the past, so maybe test with a different eco?

I used that Slimefun 4.9-canary-fb2fbce and Java 11
Residence v4.9.3.5, CMI v8.8.4.2

**Comment by ImFunnySun** [comment]
Thanks! I have been solve out the problem!
