### ISSUE TITLE
Send translated material to player

### ISSUE THREAD

**Issue by ahdg6** [Unprotesting/Auto-Tune#30]
So far,you have done with message file.But that's not enough,Making material translateable will be awesome.
You can use [LocaleLib](https://github.com/PikaMug/LocaleLib) to do it.
Just shade it into your jar as it was lisenced by MIT.

**Comment by Unprotesting** [comment]
I'm working on developing messages are displayed and configured. I'll look into using this library to develop that.

**Comment by Unprotesting** [comment]
If this is still an issue please re-open it or use our discord.
