### ISSUE TITLE
[BUG] Error in task 15

### ISSUE THREAD

**Issue by AllPlayed** [Unprotesting/Auto-Tune#35]
**Describe the bug**
Crash / Error in Task 15

**To Reproduce**
I don't know how can this be reproduced, it appeared from nowhere.

**Error**
`02.12 00:06:24 [Server] WARN [[AUTO-TUNE]] Plugin Auto-Tune v0.13.0 generated an exception while executing task 15
02.12 00:06:24 [Server] INFO java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getBoolean(String)" because the return value of "org.bukkit.configuration.ConfigurationSection.getConfigurationSection(String)" is null
02.12 00:06:24 [Server] INFO at unprotesting.com.github.events.async.PriceUpdateEvent.updateItems(PriceUpdateEvent.java:57) ~[Auto-Tune-0.13.0.jar:?]
02.12 00:06:24 [Server] INFO at unprotesting.com.github.events.async.PriceUpdateEvent.calculateAndLoad(PriceUpdateEvent.java:42) ~[Auto-Tune-0.13.0.jar:?]
02.12 00:06:24 [Server] INFO at unprotesting.com.github.events.async.PriceUpdateEvent.<init>(PriceUpdateEvent.java:30) ~[Auto-Tune-0.13.0.jar:?]
02.12 00:06:24 [Server] INFO at unprotesting.com.github.Main.lambda$setupEvents$2(Main.java:165) ~[Auto-Tune-0.13.0.jar:?]
02.12 00:06:24 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-377]
02.12 00:06:24 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-377]
02.12 00:06:24 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-377]
02.12 00:06:24 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
02.12 00:06:24 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
02.12 00:06:24 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Minecraft Server Version**
1.17

**Plugin List**
Essentials, Vault

**Comment by Unprotesting** [comment]
Please send your shops.yml file on discord or via discord.

**Comment by AllPlayed** [comment]
Hi there! I sent you the file in a ticket in Discord!
