### ISSUE TITLE
[BUG] /loan is utterly broken

### ISSUE THREAD

**Issue by TheWordSmith123** [Unprotesting/Auto-Tune#36]
**Describe the bug**

 - Can /loan negative amounts
 - /loan only accounts for value of current loan when determining if bal-loan>1000.
 - If a player with a loan is offline, /loan doesn't open the menu.
 - 
**To Reproduce**
1.  Go to '....'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

- Server: WarWings.minehut.gg is experiencing all these issues.

**Expected behavior**

- Not be able to loan negative amounts
- Be able to check current loans
- Not have outstanding loans greater than current balance.

**Screenshots**

**Minecraft Server Version
1.17

**Additional context**

**Comment by Unprotesting** [comment]
I can not reproduce 

""
Be able to check current loans
Not have outstanding loans greater than current balance.
""

Could you please provide a more detailed explanation on steps to achieve this. Also, can I confirm this is on 0.13.0?
