### ISSUE TITLE
[BUG] Plugin dont load properly in Arcligth

### ISSUE THREAD

**Issue by DaDiGui** [Unprotesting/Auto-Tune#48]
**Describe the bug**
When I run the /plugins command, it appears to me that it has loaded perfectly, in green color.
It even detects the commands but they don't do anything when I execute them.
I don't get any error in console when executing any command of the plugin either.
**Steps To Reproduce**
1. instal the plugin
2. run the server
3. try to open a /shop ores

**Expected behavior**

**Minecraft Server Version**
1.18.2 etc.

**Auto-Tune-Version**
0.14.0-pre-release

**Additional context**
**LOG:**https://pastebin.com/rJn87gdz
**Plugins (12)**: ArclightPatcher, LuckPerms, NBTAPI, Vault, Auto-Tune, PlaceholderAPI, Core, ProtocolLib, Bank, HolographicDisplays, XConomy, BetonQuest

**Comment by Unprotesting** [comment]
This is because Auto-Tune relies on the Adventure API which only supports Paper, Sponge and Velocity. (As well as their forks). I can hopefully find a workaround so it will work on other versions but for now that's the reason the plugin isn't working.

**Comment by Unprotesting** [comment]
Auto-Tune depends on the Adventure API for all messages it will be a lot of work to fix the plugin so it works with spigot. Arclight is planning to support paper plugins, shown in their [FAQ](https://github.com/IzzelAliz/Arclight/wiki/FAQ). For now we will only be supporting paper servers. Paper is a far better server software than spigot or spigot forks, faster, more stable, better API's, more support etc. Please read about them on their website [here](https://papermc.io/).
