### ISSUE TITLE
(Question) SelfHost Auto-Tune API instance

### ISSUE THREAD

**Issue by NickAcPT** [Unprotesting/Auto-Tune#6]
This isn't an issue, but a question regarding the API.

Is it possible to Self-Host the Auto-Tune API? If not, will there be in the future, or is this just for the money?

Am asking because I find it rather disappointing that the backend isn't also open-source and free to host on our side. I understand the cloud pricing, but providing a self-hosting way is something interesting to some end users.

**Comment by Unprotesting** [comment]
The Auto-Tune API wont be free too the public, _at least for the time being_. Open-sourcing our whole project we feel wont support our team enough. Once we develop more models we may release some, like the Basic/Advanced to the public but not right now. However, we are giving out free keys until the end of September. Parts of the algorithms exist locally to reduce unneeded data transfer from your server to ours so parts of the model are self-hosted. Is the reason you want the API to be open-sourced? Are you trying to see the code or are you interested in using the API yourself?

**Comment by Unprotesting** [comment]
Closing this issue because of no reply.
