### ISSUE TITLE
Is it possible to add custom items with an itemadder?

### ISSUE THREAD

**Issue by XionioXMaster** [Unprotesting/Auto-Tune#74]
Is it possible to add item support itemadder?

**Comment by Unprotesting** [comment]
What do you mean by this exactly?

**Comment by XionioXMaster** [comment]
> What do you mean by this exactly?

For example, I want to sell an item that has its own NBT tag

As I understand it is not possible in the plugin, or I just need the code ((

**Comment by Unprotesting** [comment]
Created issue #77 to tackle this. If you want to track development or have any questions you can ask them there.
