### ISSUE TITLE
[BUG] Used items can be sold via /sell

### ISSUE THREAD

**Issue by pavl21** [Unprotesting/Auto-Tune#83]
**Describe the bug**
Used items like pickaxes or shovels can be sold via /sell

**Steps To Reproduce**
Sell pickaxe via /sell

**Expected behavior**
Item is not sold

**Minecraft Server Version**
1.19 etc.

**Auto-Tune-Version**
0.13.0 etc.

**Additional context**
...

**Comment by Unprotesting** [comment]
This is fixed by the "durability-function" setting that has been created for 0.14.1.
