### ISSUE TITLE
[BUG] java.lang.ArrayIndexOutOfBoundsException: null

### ISSUE THREAD

**Issue by pavl21** [Unprotesting/Auto-Tune#89]
**Describe the bug**
See screenshot
**Steps To Reproduce**
idk
**Expected behavior**

![image](https://user-images.githubusercontent.com/36771750/190727495-9ef3e002-4875-4bea-9c36-f042569ba9cf.png)

**Minecraft Server Version**
1.19 etc.

**Auto-Tune-Version**
0.13.0 etc.

**Additional context**
java.lang.ArrayIndexOutOfBoundsException: null

**Comment by Unprotesting** [comment]
Please test on 0.14.0 and reopen issue.
