### ISSUE TITLE
[BUG]No change after modifying max-buy and max-sell

### ISSUE THREAD

**Issue by jason920612** [Unprotesting/Auto-Tune#92]
**Describe the bug**
No change after modifying max-buy and max-sell
![image](https://user-images.githubusercontent.com/30766214/190885188-86019919-8113-4276-b3e4-42433fde4579.png)

**Steps To Reproduce**
Open the server after modifying the settings

**Expected behavior**
Correct change in quantity

**Minecraft Server Version**
1.19 etc.

**Auto-Tune-Version**
0.14.0 etc.

**Comment by jason920612** [comment]
After deleting data.db, it works fine
Is it necessary to delete data.db for each modification?

**Comment by Unprotesting** [comment]
It should not be necessary to delete data.db. Will try to replicate and could be a possible bug.

**Comment by Unprotesting** [comment]
Changing max-buy and max-sell works on a restart for me but not on running /shop update. Will work on this now.

**Comment by Unprotesting** [comment]
Actually I can't reproduce. This works fine for me and is not a bug.

**Comment by LcyDev** [comment]
This is also happening to me
