### ISSUE TITLE
[BUG] The price of emeralds will go to zero

### ISSUE THREAD

**Issue by KageRyo** [Unprotesting/Auto-Tune#94]
**Describe the bug**
The price of emeralds will go to zero and can be bought and sold infinitely, and some goods also have this situation, resulting in players being able to launder money

**Steps To Reproduce**
Players who buy and sell diamonds and emeralds will automatically catch them again when they re-enter /shop after the number of times.

**Expected behavior**
Database issues need to be revisited.

**Minecraft Server Version**
1.19 etc.

**Auto-Tune-Version**
0.13.0 etc.

**Comment by Unprotesting** [comment]
Please test on 0.14.0 and reopen issue.
